# Generated by Django 3.2.16 on 2022-11-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_ingredients_ingredient'),
        ('login', '0003_alter_bookmarks_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userbookmarks',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Recipe'),
        ),
    ]
