# Generated by Django 3.2.16 on 2022-11-16 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('servingQuantity', models.CharField(blank=True, choices=[(None, 'Your String For Display'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('8+', 'More than 8')], max_length=15, null=True)),
                ('skillLevel', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('prepHour', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0, null=True)),
                ('prepMin', models.CharField(blank=True, choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], max_length=7, null=True)),
                ('cookHour', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0, null=True)),
                ('cookMin', models.CharField(blank=True, choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], max_length=7, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipe_img', models.ImageField(default='post.jpeg', upload_to='images/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_User', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=240)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_Steps', to='recipes.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitywhole', models.CharField(blank=True, max_length=2, null=True)),
                ('quantityfraction', models.CharField(blank=True, choices=[('1/4', '1/4'), ('1/3', '1/3'), ('1/2', '1/2'), ('2/3', '2/3'), ('3/4', '3/4')], max_length=8, null=True)),
                ('unitId', models.CharField(choices=[('cup', 'Cup'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('pint', 'Pint'), ('quart', 'Quart'), ('ounce', 'Ounce'), ('dozen', 'Dozen'), ('can', 'Can'), ('bunch', 'Bunch'), ('whole', 'Whole')], max_length=10)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_Recipes', to='recipes.recipes')),
            ],
        ),
    ]
